<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pxa_recipe_db"
 *
 * Auto generated by Extension Builder 2015-12-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Recipe database',
	'description' => 'A simpe recepie plugin, list and detail view',
	'category' => 'plugin',
	'author' => 'Pixelant',
	'author_email' => 'info@pixelant.se',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);